### ISSUE TITLE
Intl.DateTimeFormat.prototype.formatToParts's length should be changed to 1 to follow #76

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#133]
The length of function returned from `Intl.DateTimeFormat.prototype.format` was changed from 0 to 1 in the 2nd edition (#76). So I think we should change `Intl.DateTimeFormat.prototype.formatToParts`'s length to be also 1, so it's consistent with `Intl.DateTimeFormat.prototype.format`.

/cc @zbraniecki

**Comment by zbraniecki** [comment]
@caridy

**Comment by littledan** [comment]
SGTM

**Comment by caridy** [comment]
Yes! @zbraniecki can you send a PR?

**Comment by caridy** [comment]
Actually, but looking at the spec, we intentionally removed the length for well defined prototype methods, and we only add it when it is ambiguous, like the case of [anonymous built-in functions for datetimeformat](https://tc39.github.io/ecma402/#sec-datetime-format-functions). In 402, we have 3 of those, (all 3 `.format()` functions). I noticed that "Collator Compare Functions" doesn't have that specified, we should add it there for sure.

In the case of `formatToParts()` we don't do all the gymnastics that we normally do for `.format()`, instead it is just a prototype method, and there is no ambiguity with the length.

Maybe @bterlson can clarify, because I'm not sure anymore.

**Comment by littledan** [comment]
For `formatToParts`, the parameter is in square brackets, making it optional. An alternative to the patch adding the note specifying a length would be to remove those brackets, making the implicit length 1.
