### ISSUE TITLE
Provide an access to CLDR database shipped in browser

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/ecma402#266]
Most of ECMA402 features polyfills are forced to ship part of CLDR database with them. Browsers already ship CLDR so it'll be nice to have some CLDR API with getters to reuse CLDR data in polyfills/libraries

**Comment by jackhorton** [comment]
This has been brought up before, such as in https://github.com/tc39/ecma402/issues/210. The issue is open but general discussion seems cold (my initial reaction is that its an enormous surface area to cover and rife with compatibility concerns, but I haven't thought about it too much). Does that issue cover your concerns or is this slightly different?

**Comment by chicoxyzzy** [comment]
@jackhorton yes, thank you. I'll close this issue than
