### ISSUE TITLE
Locale canonicalization: Some variant subtag canonicalization is not useful when following the letter of BCP 47

### ISSUE THREAD

**Issue by jungshik** [tc39/ecma402#273]
intl402/Locale/constructor-non-iana-canon.js has 

```
    {
        tag: "es-ES-preeuro",
        maximized: "es-Latn-ES-preeuro",
        minimized: "es-preeuro",
    },
    {
        tag: "uz-UZ-cyrillic",
        maximized: "uz-Latn-UZ-cyrillic",
        minimized: "uz-cyrillic",
    },
    {
        tag: "hi-direct",
        maximized: "hi-Deva-IN-direct",
    },
    {
        tag: "zh-pinyin",
        maximized: "zh-Hans-CN-pinyin",
    },
    {
        tag: "zh-stroke",
        maximized: "zh-Hans-CN-stroke",
    }
}
```

v8 fails the test because ICU converts 'zh-stroke' to 'zh-u-co-stroke', 'es-preeuro' to 'es-u-cu-esp', and so forth. 

What ICU does is much more sensible and arguably better for users. 

@gsathya

**Comment by jungshik** [comment]
BCP 47 cannot mention what Unicode extension can do. So, variant tag needs to be just preserved over canonicalization. And, they cannot be listed in the IANA subtag registry, either (or maybe they can ?)  However, RFC 6067 (u-extension) and CLDR know more and do more useful things as shown above.

**Comment by jungshik** [comment]
@jackhorton @littledan @jefgen

**Comment by jackhorton** [comment]
One thing to note about ICU converting "es-preeuro" to "es-u-cu-esp" is that Intl doesn't support the -cu extension, so that extension will *always* get lost in locale processing. If it was canonicalized to es-preeuro, though, that would persist through language processing as a valid variant, and then... something? would happen when it came time to actually ask ICU to format a currency using, lets say, the Euro.

```js
new Intl.NumberFormat("es-ES-preeuro", { style: "currency", currency: "EUR" }).format(1.5) // => ????
```

**Comment by stpeter** [comment]
@jungshik It's not clear to me what your question is. However, you might want to ask @aphillips (co-author of BCP 47 and RFC 6067).

**Comment by aphillips** [comment]
@jungshik variant subtags absolutely *are* in the IANA subtag registry (or they are not valid). Some of the tags you mention in `intl402/Locale/constructor-non-iana-canon.js` are invalid. The shown ubtags such as `cyrillic`, `preeuro`, `direct`, and `stroke` appear to refer to features of the Unicode locale extension, the transliteration extension, or to special usage (and thus should be introduced by `-x`). None of those tags are valid and I'm distressed to see them in 402.

@jackhorton if Intl doesn't support a given keyword, I think it would be a bug to strip it out when canonicalizing the locale. The canonicalization rules for BCP47 and RFC6067 are independent of the contents of the subtag registry or the CLDR locale spec and this is on purpose (in part to help implementers write code that isn't constantly peering into this or that data file). Ignoring stuff we don't understand (yet) is better than losing data someone else might consume. Inventing ways to encode things that are validly encoded elsewhere (such as creating variant subtags mentioned above) is even less helpful--releasing (in this case) BCP47 *in*valid tags in the wild.

**Comment by jungshik** [comment]
I just mentioned you to get your attention. You need to go to the GitHub to
actually see the issue by following the link in the email.

Jungshik

**Comment by jackhorton** [comment]
I believe that bug is encoded in our spec for our existing constructors :) https://tc39.github.io/ecma402/#sec-resolvelocale strips the locale to the basename + extensions (2.a and 3.a, really part of #sec-bestavailablelocale) and then selectively adds back extensions that 1) the constructor explicitly supports (step 8.h.i - ex: for Collator, we only support co, kn, and kf) and 2) that we have data for (step 8.h.ii.1.a - ex, we support de-u-co-phonebk but not de-u-co-nothing in common implementations).

Intl.Locale, being discussed here, uses a slightly different path that I don't know as well off-hand (even though I just implemented it, its fairly complex). V8 seems to not touch "de-u-cu-EUR" for basic construction, but cu is removed during maximization and a rangeerror is thrown for minimization. Chakra's Locale implementation currently handles unexpected Unicode extensions by preserving and ignoring them, which sounds like what you think should happen? Regardless, the bit above about the other constructors stripping it means it will never pass through a functional constructor unscathed.

**Comment by macchiati** [comment]
We do handle some legacy bogus bcp47 subtags, translating to equivalent conforming unicode locale identifiers.

I'm surprised by preeuro. I don't remember ICU doing anything with it. Yoshito would know.

**Comment by aphillips** [comment]
@jackhorton maximization (which I mentally equate with "addLikelySubtags") seems like it shouldn't remove stuff. Minimization is necessarily messy. I'm fine with things like Collator throwing out stuff that doesn't matter--seems like a good idea. To be totally honest, I'm not a huge fan of decorating locale IDs with a lot of these preferential details. A lot of this stuff is specific to a given operation and the tags were baroque enough before there were *any* extensions. I don't necessarily have a good answer, except to say that the less we veer away from consistent tag processing (by which I mean "what I described above") the more I like it. @macchiati and I differ a little bit in this regard.

*Aside*: A tag like `es-preeuro` is kind of devoid of meaning, since, lacking a region, it can't exactly set the default currency and that's the only meaningful thing such a subtag can do. Note that some pre-Euro locales used different formats for their currencies, famously `pt-PT-u-cu-PTE`, from those adopted when they acceded to the Euro, so maybe that's what the subtag is trying to get at? Note too that some countries that adopted the Euro had more than one currency code pre-Euro. Your [example ](https://github.com/tc39/ecma402/issues/273#issuecomment-423599974) of `es-ES-preeuro` with `currency:EUR` is easily solved, at least in my mind. Implementations should always take an explicit currency over a default one. (Anyone who sends currency values around as naked numbers without a currency code associated somehow is asking for trouble. That's what relying on the default currency of the locale really means in practice.)  

That's my PTE 00$02 ;-)

**Comment by jungshik** [comment]
Thank you everybody for adding comments. It helped me form 

@aphillips wrote: 
> None of those tags are valid and I'm distressed to see them in 402.

Don't worry.  They're not a part of Ecma 402 spec, but it's included in test262/intl402 (perhaps coming from Mozilla) to make sure that [ICU's extra mapping entries (non-registered mapping entries)](https://github.com/unicode-org/icu/blob/e8159dee5bd990daf1d3c4b0c9a2f9b2d34e2037/icu4c/source/common/uloc.cpp#L468) do not creep in.  

As @macchiati wrote, quite a few legacy bogus BCP 47 subtags are mapped to _U-extension-equivalent_ by ICU (see [this part of ICU's uloc.cpp](https://github.com/unicode-org/icu/blob/e8159dee5bd990daf1d3c4b0c9a2f9b2d34e2037/icu4c/source/common/uloc.cpp#L468)  ).  

Given that those bogus legacy variant subtags ('cyrillic', 'direct', 'preeuro', 'pinyin', 'traditional', etc ) are pretty rare and they can be expressed in a modern standard way (or in case of currency, it has dubious value/uncertain interpretation), there's no point of _polluting_ Ecma 402 spec by adding exceptional handlings for those legacy variant substags.    So, I think this issue can be closed.  Instead, I'll file a FR against ICU to have a _**strict/pure BCP 47 + RFC 6067 + IANA language subtag registry mode**_ . 



@aphillips also wrote: 
> Anyone who sends currency values around as naked numbers without a currency code associated somehow is asking for trouble. That's what relying on the default currency of the locale really means in practice

I can't agree more. My bank (I'd not name it here :-)) makes my account balance about 1/1000 smaller when I put ko-KR at the top of my Accept-Language list ;-).   I guess that is one of reasons why 'cu' was not included in the list of u-extension keys to support in Ecma 402 (Thanks, @jackhorton , for pointing that out).

**Comment by jungshik** [comment]
https://unicode-org.atlassian.net/browse/ICU-20167 was filed against ICU. @FrankYFTang

**Comment by littledan** [comment]
Wait, do we want to follow the letter of BCP 47, or do we want to consider Unicode Language IDs? cf https://github.com/tc39/proposal-intl-locale/issues/63

**Comment by jungshik** [comment]
Even in "Unicode BCP 47 locale id",  my hope is that variants such as preeuro, pinyin, cyrillic and traditional are not to be given special context-dependent treatment.

**Comment by jungshik** [comment]
Basically, I'm taking back the following I wrote in the bug report. 

> What ICU does is much more sensible and arguably better for users.

**Comment by macchiati** [comment]
None of {preeuro, pinyin, cyrillic, traditional} are allowed in Unicode BCP
47 locales.

Mark

**Comment by jungshik** [comment]
@macchiati   That's great. Thank you for the clarification.
