### ISSUE TITLE
Needs clarification to a hour formatting

### ISSUE THREAD

**Issue by inoyakaigor** [tc39/ecma402#283]
Today I got the same situation:
https://bugs.chromium.org/p/chromium/issues/detail?id=527926

In last comment with resolution WontFix written "This is working as intended and following the spec". This behavior of browsers is wrong and needs to be clarified

**Comment by littledan** [comment]
Maybe what we're seeing here is actually missing data at the CLDR level (I might have misdiagnosed the issue in that bug, but it still doesn't seem like Chrome's or ECMA-402's fault).

**Comment by inoyakaigor** [comment]
@littledan Issue that when option `hour` set to `2-digit` I expecting result `03` but getting `3` like option `hour12` set to `true`.

If it isn't ECMA-402 fault please get me link to right place to fill a issue

**Comment by sffc** [comment]
ECMA 402 behavior returns the "best match" format; if no locales have data for `hour: "2-digit"`, then you get behavior for the next best thing.

I suggest filing a bug against CLDR: https://unicode.org/cldr/trac/wiki

When you do, post a link here to cross-reference.

**Comment by littledan** [comment]
Should we make an ECMA-402 FAQ to explain this? This sort of question comes up fairly often.

**Comment by inoyakaigor** [comment]
@sffc My English is not good enough to explain the situation in a bug. Can you help me with it?

**Comment by sffc** [comment]
Done: https://unicode.org/cldr/trac/ticket/11953

**Comment by sffc** [comment]
Peter Edberg replied to the CLDR bug:

> Don't need more skeletons. DateTimePatternGenerator has a version of getBestPattern that takes options:
>
> ```
>  UnicodeString icu::DateTimePatternGenerator::getBestPattern     (const
>  UnicodeString &skeleton,
>  UDateTimePatternMatchOptions options, UErrorCode & status);
> ```
>
> and one of those options is
>
> ```
> UDATPG_MATCH_HOUR_FIELD_LENGTH
> ```
>
> This option is just not exposed in the setup vua DateFormat as above.

@FrankYFTang @anba Is fixing this issue just a matter of enabling that flag in the Intl code?

**Comment by FrankYFTang** [comment]
I have no idea, but the behavior on https://bugs.chromium.org/p/chromium/issues/detail?id=527926 is different now. Maybe that is because I fixed some other bugs.
On V8 now (and also chrome m73)

V8 version 7.5.0 (candidate)
d8> var formatter = new Intl.DateTimeFormat('ru', {hour:'2-digit', minute: '2-digit'})
undefined
d8> formatter.format(new Date(2015, 8, 1, 3, 0, 0))
"03:00"
d8> new Intl.DateTimeFormat('ru', {hour:'2-digit', minute: '2-digit', hour12: false}).format(new Date(2015, 8, 1, 3, 0, 0))
"03:00"
d8>  new Intl.DateTimeFormat('ru', {hour:'2-digit', minute: '2-digit', hour12: true}).format(new Date(2015, 8, 1, 3, 0, 0))
"3:00 AM"

Either way, this is an implementation issue and if there are issue should file against each browser but not in the ECMA spec. I suggest we close this issue.

**Comment by FrankYFTang** [comment]
Is the issue that the last one should be "03:00 AM" instead?

**Comment by FrankYFTang** [comment]
chrome fix in https://chromium-review.googlesource.com/c/v8/v8/+/1529260 since this is not a spec issue, I mark this issue close.

**Comment by inoyakaigor** [comment]
> Is the issue that the last one should be "03:00 AM" instead?

I think so, because the number of digits is explicitly specified

**Comment by sffc** [comment]
Thanks for the quick fix, Frank!

For reference: here is the Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1284868

I don't have Safari right now so I can't verify on Safari.  Can someone check whether Safari has the same problem?

**Comment by inoyakaigor** [comment]
@sffc 
MacOS 10.14.3 / Safari 12.0.3 (14606.4.5) 
![image](https://user-images.githubusercontent.com/1235286/54647595-1e093780-4ab4-11e9-971d-a12c32b41e18.png)

**Comment by sffc** [comment]
Great, thanks.  Here is the Safari bug: https://bugs.webkit.org/show_bug.cgi?id=195974
