### ISSUE TITLE
Permit the use of tailorings NOT in CLDR

### ISSUE THREAD

**Issue by srl295** [tc39/ecma402#299]
- Followon to https://github.com/tc39/ecma402/pull/291
- Rather than just permitting looking at CLDR, we should allow implementations to have their own tailorings— with CLDR being recommended, of course, but not restricting implementations.  Look at how CLDR itself and Unicode structure conformance clauses for example text.
- Consider some front (or back matter, https://tc39.github.io/ecma402/#annex-implementation-dependent-behaviour ) to discuss this kind of tailoring, "CLDR or local tailioring" so that it can be referred to or at least not repeated many times in the spec.

**Comment by srl295** [comment]
Discussed during https://github.com/tc39/ecma402/blob/master/meetings/agenda-2018-11-26.md

**Comment by littledan** [comment]
Thanks for filing the issue. Yes, we'll need a PR for this. Any takers?

**Comment by anba** [comment]
Do we plan to require that at least the tailorings defined in SpecialCasing.txt must be supported? Because if any implementation-defined tailoring is allowed, implementations could choose to not support any locale-specific tailoring, which would mean the tests in <https://github.com/tc39/test262/tree/master/test/intl402/String/prototype/toLocaleLowerCase> and <https://github.com/tc39/test262/tree/master/test/intl402/String/prototype/toLocaleUpperCase> need to be removed, because they expect that the locale-specific tailorings from SpecialCasing.txt are implemented.

**Comment by littledan** [comment]
@anba About removing tests: We could instead use the test262 `locale:` metadata to indicate that they contain assumptions about the locale data, rather than removing the tests. We should probably do this whether or not we require SpecialCasing.txt, since the test will be effectively checking that there are no *additional* tailorings.

**Comment by spectranaut** [comment]
fixed in #341
