### ISSUE TITLE
MDN for Intl.PluralRules missing Digits options

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#378]
Following on https://github.com/tc39/ecma402/issues/365#issuecomment-530623312

I made the edit on MDN (and it seems to get saved) but I'm not sure if that's the right way to do it? Is there a contribution doc?

**Comment by sffc** [comment]
@romulocintra @jahzielv

**Comment by romulocintra** [comment]
Hi @longlho  thanks for your contribution on MDN, we recently started "trying" to have a certain order and tracking regarding the documentation.

At the moment we are focused on following "new" proposals that don't have or have a short documentation in MDN (Example of issue [Intl.RelativeTimeForma](https://github.com/tc39/proposal-intl-relative-time/issues/102)). 

Assuming that documenting new and existent API's shouldn't be a one time github issue probably we should agree in opening small issues to track small updates instead of having one that holds small tasks. 

Organizing the way we document , track and organize the people that can give a hand on that should be probably a good topic in one of the next Meetings for 402. Do you agree @sffc ?

**Comment by sffc** [comment]
I think for MDN, first we need to make sure new PRs and proposals are fully documented in English.  In my opinion, that step should block PRs and proposals from advancing.  I added a column for it in the wiki:

https://github.com/tc39/ecma402/wiki/Proposal-and-PR-Progress-Tracking

Then, once the initial documentation is written, we can translate to more written languages, fix problems with the existing documentation (like this issue is for), etc.  However, I don't think this is the right forum to track those issues.  Is there an MDN GitHub where such issues can be filed?

**Comment by longlho** [comment]
Thanks for the info but I'm not sure if that answered my question regarding MDN contributions. Specifically what I'm looking for are:
1. Is clicking `Edit` on the MDN page the correct way to make changes?
2. Is there some PR flow for MDN changes, or is this maintained similarly to wikipedia where everyone can make changes?

**Comment by jahzielv** [comment]
Hi @longlho, great questions, and thanks for your contribution!

1.  Yep, that's correct! Just clicking `edit` will let you make the changes to the pages.
2. Exactly right – MDN is a wiki-style site, where anyone can make changes. There are folks at Mozilla as well as volunteer moderators that review changes, but there's not a PR flow for changes to land.

**Comment by longlho** [comment]
Gotcha thanks!
