### ISSUE TITLE
All string literals must be code formatted

### ISSUE THREAD

**Issue by rwaldron** [tc39/ecma402#54]
@bterlson why have you changed the convention for string literals?

![](https://i.gyazo.com/8c3dbe348104be74bfa9f7cacba94ff6.png)

to: 

![](https://i.gyazo.com/7a667c2287d85fb9d08c718acd7a6cf9.png)

**Comment by bterlson** [comment]
Caridy just pointed me to this, sorry. It was changed as it was annoying - some quotes aren't the start of strings. In general, \*'s are used for values, so it makes sense to use them for string values as well.

**Comment by spectranaut** [comment]
It looks like Ecma-262 has two conventions for string literals now.

In [String.prototype.normalize](https://tc39.es/ecma262/#sec-string.prototype.normalize) we see ``` `"string"` ```:
 ```If _f_ is not one of `"NFC"`, `"NFD"`, `"NFKC"`, or `"NFKD"`, throw a *RangeError* exception.```

Then in [String.prototype.padStart](https://tc39.es/ecma262/#sec-string.prototype.padstart) we see ``` *"string"* ```:
```Return ? StringPad(_O_, _maxLength_, _fillString_, *"start"*).```

Which is correct? Ecma-402 only uses ``` `"string"` ```. Should we change to ``` *"string"* ``` as seems to be @bterlson's preference from 3 years ago? :) @leobalter @sffc @ljharb

**Comment by ljharb** [comment]
cc @rkirsling, who i believe has an open PR to unify these conventions?

**Comment by rkirsling** [comment]
It's true that updating <code>\`"foo"\`</code> → <code>\*"foo"\*</code> is meant to follow https://github.com/tc39/ecma262/pull/1302, which mainly addresses the current inconsistency in <code>\`foo\`</code> vs. <code>\`"foo"\`</code> for properties, but that's one already been open for a year, so it's completely taken the wind out of my sails... :sob:

**Comment by ljharb** [comment]
I plan to merge that PR within the next few weeks, for the record, just after merging a few others that need to be prioritized (and after rebasing 1302), with perhaps minimal adjustments - so I think that perhaps 402 should hold off making any changes until after that lands, at which point the overarching convention in 262 will be `*"string"*`, and then 402 could make that change?

**Comment by rkirsling** [comment]
Yay! Sounds like a plan to me.

**Comment by ljharb** [comment]
https://github.com/tc39/ecma262/pull/1302 has been merged.

**Comment by sffc** [comment]
Excellent.  @spectranaut @leobalter can you follow up with a PR to ECMA-402 following the latest convention of ECMA-262?

**Comment by spectranaut** [comment]
Yup, I can do this Thursday.

**Comment by spectranaut** [comment]
Wow, I can believe that after doing this work I'm convinced we should leave all string literals as  `` `"string"` `` instead of changing it to  `*"string"*`, especially given the changes @rkirsling made.

Ultimately, I was convinced for mostly two reasons:

1. I think it will be confusing for future contributors to know when to use which convention. If property names look like strings (because they are quoted) but you use the `*"string"*` convention, AND all other string literals use the `` `"string"` `` convention, I think contributors who are newer to the spec will make endless mistakes (where someone just copies either convention for their string literals or properties).

2. Unlike we assume above, the majority of the string literals in 262 still use the  `` `"string"` `` convention. And all of 402 does. I'm used to seeing string literals in the consolas font family and I image most contributors/readers of the spec are as well. See the example screenshots below.

I'd like to close this and open an issue on 262 to change the few string cases that use `*"string"*`  back to `` `"string"` ``, unless @ljharb or @rkirsling can provide overriding reasons to switch both specs to `*"string"*` anyway?

#### For an example, look how weird this table looks (and the following algorithm) if we change the string literals and not the properties:
![confusing-convention](https://user-images.githubusercontent.com/583831/66605761-acdbbf80-eb7e-11e9-899c-57643bf49894.png)

#### For reference, the spec as it is now:
![not-confusing-convention](https://user-images.githubusercontent.com/583831/66605791-ba914500-eb7e-11e9-9751-42e730f4ed37.png)

**Comment by rkirsling** [comment]
Sorry @spectranaut, I meant to add a clarification after [this comment](https://github.com/tc39/ecma402/issues/54#issuecomment-538405839) but failed to do so. tc39/ecma262#1302 was merely the long-standing _prerequisite_ for doing the parallel work in 262.

The plan is that after tc39/ecma262#1724 and tc39/ecma262#1725 are merged, _all_ remaining cases of <code>\`"foo"\`</code> would be converted to <code>\*"foo"\*</code> in one fell swoop.

**Comment by spectranaut** [comment]
Oh right I think I understand, but I still think we shouldn't do it! I don't think I agree that `` `"foo"` `` should be converted to `*"foo"*`.

**Comment by ljharb** [comment]
So to paraphrase, you're saying you don't think we should differentiate property names (identifiers) - from string values (which are not limited to identifiers)?

**Comment by rkirsling** [comment]
You're also right that asterisks here are a new stylistic convention and absolutely not a correction of some outlier cases. The idea (first suggested to me by @bterlson [here](https://github.com/tc39/ecma262/pull/1239#pullrequestreview-143006612)) is that it's an oddity that strings are the only type of ECMAScript language value which aren't stylized as one, and this would be worth correcting in spite of its long history.

As to confusion, it's certainly been highly problematic that we've never documented this in one way or another up until now, but this documentation is included in tc39/ecma262#1725.

**Comment by spectranaut** [comment]
Right @ljharb, I don't think they should be styled differently. I don't think they need to be -- I think it reads very clearly when they are styled the same.

**Comment by rkirsling** [comment]
@ljharb That differentiation is temporary though. 😞

To reiterate, the primary purpose of tc39/ecma262#1302 was adjusting <code>\`foo\`</code> to <code>\`"foo"\`</code> for properties. I know some other changes snuck in too, and I'm sorry for that, but "asterisks for strings" is 100% a follow-up that has yet to be performed.

I thought that it would be safe for 402 to move in parallel by simply ignoring the weird current state of 262, but I didn't convey this information clearly...

**Comment by rkirsling** [comment]
Okay! So with tc39/ecma262#1725 and tc39/ecma262#1733 landed, this should now be as clear and straightforward as this thread initially suggested.

Apologies again for all the confusion. :bow:

**Comment by spectranaut** [comment]
Oh, I finally understand. Thanks @rkirsling and @ljharb, I'll do the same to 402.
