### ISSUE TITLE
Add abstraction operations for type validation

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#567]
In 

https://github.com/tc39/intl-displaynames-v2/issues/25#issuecomment-819888506
@ryzokuken  suggest we add Abstract Operation 

>You should atleast change the new one to match the other and perhaps better, refactor the check into a simple abstract operation, perhaps called IsValidCalendar. One thing to note is that Temporal goes a step further and defines the grammar. Perhaps we should reference that so that worst case we're referring to an ECMA document and best case we'd be referring to something from ECMA-262 (soon hopefully).
>I can understand if you want to wait until Temporal is Stage 4, but perhaps we should atleast unify the calls in a single AO so it can be easily done later.

These may be needed for 
IsWellFormedCalendar / IsWellFormedCollation / IsWellFormedNumberingSystem or even IsWellFormedLanguage / IsWellFormedRegion / IsWellFormedScript . But I think that should be done via a Editorial PR in ECMA402 instead.

**Comment by ryzokuken** [comment]
I felt this most strongly about `IsValidCalendar` because there's already two separate places where Calendar validation is being done and it would be a nice idea to unify those callsites. That said, I'd be happy to see all of them but it is most important for those which are validated at two or more distinct places in the spec.

**Comment by FrankYFTang** [comment]
I read the spec again and I think if we want to put the abstract operation there, it should be named as IsWellFormedXXX to indicate the well form of the syntax, not IsValidXXX

**Comment by ryzokuken** [comment]
Oh sure, I had not spent time figuring out what the name should be.

**Comment by ben-allen** [comment]
As of @FrankYFTang's a01daff9fe6e15a707e9fc5d9ac4876f55541157 the inconsistency in calendar validation wording was fixed. Is there still interest in moving this validity check and other similar validity checks to their own AOs? For whatever it's worth, I'm skeptical of the idea, but can be persuaded otherwise. @ryzokuken @gibson042

**Comment by gibson042** [comment]
I share your skepticism.

**Comment by sffc** [comment]
I think this type of refactoring can be done later when it is needed.
