### ISSUE TITLE
Non-ASCII characters are inconsistently represented

### ISSUE THREAD

**Issue by gibson042** [tc39/ecma402#634]
cf. https://github.com/tc39/ecma402/pull/621#discussion_r769059711 :
> ECMA-262 prefers HTML character entities and ECMA-402 should follow suit. But we'll probably just update everything at once.
> 
> ```shell
> $ egrep --no-filename -ro \
>   '[^][\n !"#$%&'\''()*+,./0-9:;<=>?@A-Z\\^_`a-z{|}~-]|&[[:alnum:]]*;' spec/ | \
>   sort | uniq -c
>      10 ×
>      11 ≠
>       3 ≤
>       3 ≥
>       9 §
>      23 –
>      16 𝔽
>       5 &ge;
>      84 &gt;
>       3 &infin;
>      79 &laquo;
>       2 &ldquo;
>       1 &le;
>      87 &lt;
>       1 &mdash;
>       1 &ne;
>      79 &raquo;
>       2 &rdquo;
>       1 &reg;
> ```

**Comment by ben-allen** [comment]
In the time between when this issue was initially posted and now ECMA-262 has replaced HTML character entities  (see: https://github.com/tc39/ecma262/pull/2901) with the Unicode characters they represent.  I've put up https://github.com/tc39/ecma402/pull/907, which makes character representation in ECMA-402 consistent by using Unicode characters rather than HTML entities &mdash; the representation that 262 uses now, which is the opposite of the representation they standardized on back in 2021.

**Comment by ben-allen** [comment]
Closed by https://github.com/tc39/ecma402/pull/907
