### ISSUE TITLE
Wrong era for ISO year 0 in Gregorian calendar

### ISSUE THREAD

**Issue by ptomato** [tc39/ecma402#723]
In the [[Era]] row of https://tc39.es/ecma402/#table-datetimeformat-tolocaltime-record:

> Let `year` be `YearFromTime(tz)` specified in es2023's [Year Number](https://tc39.es/ecma262/#sec-year-number). If year is less than 0, return 'BC', else, return 'AD'.

This should be "less than 1" because ISO year 0 is the year 1 BC (or 1 BCE if you prefer the "common era" nomenclature). There is no year 0 BC or 0 AD.

I ran a quick check with eshost, and none of the engines that I have installed implement the spec as written:
```
$ eshost -e 'new Date(Date.parse("+000000-01-01")).toLocaleDateString(undefined, {era:"short", timeZone:"UTC"})'
#### ChakraCore
1 1, 1 BC

#### engine262

Error: Date.prototype.toLocaleDateString is not implemented

#### GraalJS
1/1/1 BC

#### JavaScriptCore
1 1, 1 BC

#### Moddable XS
Fri Dec 31 -0001

#### QuickJS
12/31/-0001

#### SpiderMonkey
1/1/1 B

#### V8
1/1/1 BC
```
As you can see, output varies quite a lot, but for all the engines that do include an era in the output, it is always BC for ISO year 0. So this change would reflect web reality.

(Spotted by @gibson042.)

**Comment by Louis-Aime** [comment]
Let me recall what I have already expressed in other issues about the Gregorian / Proleptic Gregorian / Julian calendars.

- The strange way of counting years backwards from the origin has been established by [Bede the Venerable](https://en.wikipedia.org/wiki/Bede) in the 8th century, because there was no consensus about any "absolute" origin of times. 
- This counting method was **only applied with the Julian calendar**. Other calendars defined at ancient times did not intend to describe times before their respective origins, with the exception of the Ethiopian calendar which has conventional "Amete Amet" origin 5500 years before "incarnation" (8 AD).
- In 1740 the French astronomer Jacques Cassini used another method, 0 and negative numbers, to represent the years before "year 1 A.D.". Thus, computations are much simpler. However the historians have continued using Bede's method.
- The Gregorian reform of 1582 (applied not before 1752 in U.K. and English speaking countries) did not change the way dates were reckoned before the reform. In other words, the Gregorian calendar in Rome applies the Julian calendar until Oct. 4, 1582, and the Gregorian reckoning system from Oct 15, 1582 on, which is the next day.
- The *Proleptic* Gregorian has been used in most if not all digital platforms since it makes all computations simple and uniform. With this calendar, user specify years before 1 with relative numbers i.e. 0 and negative numbers. The legacy `Date` object works that way. The ISO 8601 standards also recommends to use negative numbers.
- There should not be any `bc` (nor `bce` era associated with any date *in the proleptic Gregorian calendar*, because this generates ambiguity and errors for the users instead of giving him any useful information. Observe that Jan. 1, 1 (Julian) is ISO 0000-12-30. 

In my option, the plain and simple ISO 8601 proleptic calendar should be used as "base" calendar, and no era indication nor `1-y` computations should be done with this calendar. 
On the other hand, a `julian` calendar should be defined for ECMA-402. It should display years with BC/AD eras.

**Comment by sffc** [comment]
While I agree with @Louis-Aime on the most correct solution, as the spec is currently written, it refers to proleptic Gregorian with eras, where 1 BCE is the proleptic Gregorian year before 1 CE.

We should _separately_ continue the discussion of whether to make `"gregory"` itself a 3-era calendar (pre-julian, julian, and gregory) instead of a 2-era calendar (bce and ce).
