### ISSUE TITLE
[Feature] Intl support for multiple formats for the same currency

### ISSUE THREAD

**Issue by khaosdoctor** [tc39/ecma402#737]
While `Intl` has a lot of support for the regionalization of currencies, we've stumbled upon some use cases that might not be covered. I brought this up in the last TC39 outreach meeting today with @romulocintra and discovered that I could open a request here for that. 

# What

As an example, in the company I work for, we use JavaScript a lot for a lot of things, including dealing with money, especially in the presentation layers. When I raised why we weren't using the `Intl.NumberFormat` spec for regionalization and formatting, I discovered that there are several ways we can format a number as a currency. Using Swedish Krona as an example, we have at least three ways to present that data:

- `SEK 111.111,56` or sometimes `111.111,56 SEK` when required for international purchases, since we need to show the currency code for exchange rates
- `111.111,56 :-` this is not widely used in digital formats but I've seen it a lot in e-commerce
- The traditional `111.111,56 kr` which is the most common abbreviation

Today, `Intl` does not support this type of formatting as it defaults to the 3rd option (which makes sense), however, it'd be a good addition to be able to choose between these types of formatting or even create a custom formatter which would allow us to specify the position and the prefix we'd like to use.

I'll find out a bit more about these use cases and try to come back with some more information here

**Comment by romulocintra** [comment]
Thanks @khaosdoctor cc @sffc

**Comment by sffc** [comment]
Please note that Intl.NumberFormat currently presents four options: "symbol", "narrowSymbol", "code", and "name", explained more [here on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#currencydisplay).

The most recent CLDR 42 release adds support for what I've sometimes seen called "global" format, which renders both the symbol and the ISO code, like `$100 USD`, but not duplicating it in cases where there is no symbol, like `100 CHF`.

CLDR also supports a "formal" style for a few currencies, such as TWD; see [here](https://unicode-org.github.io/cldr-staging/charts/latest/by_type/currencies.eastern_asia__c_.html#fc148e5b4db824).

In order to make a proposal to ECMA-402, we need to be clear on what exactly we want and what the use cases are.

**Comment by srl295** [comment]
Need more detail on the 2nd format, but the other two should be selectable via the mechanism mentioned

**Comment by khaosdoctor** [comment]
Thanks, @sffc I didn't know we had such operations! It was very clarifying! I guess these cover the first and the last use case. 

As for the second one, @srl295, I searched a bit here and found that it was an old version of "X krona and Y öre", but öre is practically defunct as most of the values are now rounded to integers, but before they were written as `25:50` meaning `25,50 kr` however when the number is whole like `25 kr`, it was written as `25:-` with the `-` representing `0`. 

I've seen these around on some sites like the image below from [here](https://www.elgiganten.se/), but mostly as price tags on stores. This is an active use case, but I've never seen decimal numbers being shown like this anywhere. And, as such, I don't know if it's a valid spec to be considered.

![image](https://user-images.githubusercontent.com/3200560/209240765-a6781b86-6f6d-45f7-b472-0d7f01d5442a.png)

**Comment by sffc** [comment]
Also worth noting that ECMA-402 supports compact currently; not really another style, but it's how you can crore/lakh formatting:

```javascript
var nf = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", notation: "compact" })

nf.format(1)
'₹1'
nf.format(10)
'₹10'
nf.format(100)
'₹100'
nf.format(1000)
'₹1T'
nf.format(10000)
'₹10T'
nf.format(100000)
'₹1L'
nf.format(1000000)
'₹10L'
nf.format(10000000)
'₹1Cr'
nf.format(100000000)
'₹10Cr'
nf.format(1000000000)
'₹100Cr'
nf.format(10000000000)
'₹1TCr'
```

**Comment by sffc** [comment]
I'm going to close this issue because it seems there isn't anything actionable from the ECMA-402 side. However, you are welcome to open an issue for consideration in CLDR, and then we can incorporate it into ECMA-402 once it is implemented over there:

https://unicode-org.atlassian.net/secure/Dashboard.jspa
