### ISSUE TITLE
ky-KG language support 

### ISSUE THREAD

**Issue by babdikaarov** [tc39/ecma402#879]
# Kyrgyzstan - region , kyrgyz - language  has no support 

```js
const locales1 = ['ky', 'KG', 'KY', 'ky-KG'];
const options1 = { localeMatcher: 'lookup' };

console.log(Intl.DateTimeFormat.supportedLocalesOf(locales1, options1));
// output: Array []
// No ky-KG language support
```

How can I contribute to add the language?

**Comment by anba** [comment]
I guess you're using Chromium, because this returns `[ "ky", "ky-KG" ]` on Firefox, but `[]` on Chromium. Chromium doesn't ship with all locale data available in [CLDR](https://github.com/unicode-org/cldr), so filing a feature request to include the Kyrgyz locale at <https://issues.chromium.org/issues> may be worth a shot.

**Comment by babdikaarov** [comment]
Thank you, @anba I submitted the issue  with id [334720108](https://issues.chromium.org/issues/334720108) on the link you provided. I will follow up with them and  I can confirm it works on Safari, Firefox but it does not work in Opera and Chromium
