### ISSUE TITLE
Intl.DateTimeFormat era: "long" outputs date in addition to era

### ISSUE THREAD

**Issue by sven-oly** [tc39/ecma402#880]
In Chrome and Firefox, this code gives:
  "20/12/2020 Anno Domini"
rather than 
  "Anno Domini"

```
const date = new Date(Date.UTC(2020, 11, 20, 3, 23, 16, 738));

console.log(
  new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Australia/Sydney',
    era: "long",
  }).format(date),
);
```

**Comment by sffc** [comment]
This is probably spec-conformant since the spec allows the implementation to load basically whatever pattern it wants, but this behavior seems surprising. Requesting only one field should produce a pattern with that one field in standalone mode. Same thing appears to happen for `timeZoneName`. However, standalone `month` and `weekday` have the expected behavior.

@zbraniecki

**Comment by anba** [comment]
Dup of #461.

**Comment by sffc** [comment]
> Dup of #461.

Indeed! Thank you.
